language: python
python:
  - 3.6
  - 3.7
install:
  - python setup.py install
  - pip install pytest pytest-cov pytest-mock codecov
script:
  - pytest --cov
after_success:
  - codecov
matrix:
  include:
    - python: 3.7
      script:
        - pip install black mypy pylint
        - pylint django_ariadne tests setup.py
        - mypy django_ariadne --ignore-missing-imports
        - black --check .